# gRPC Client - gọi tới các supporting services
grpc.client.loyalty-service.address=static://loyalty-service:9093
grpc.client.loyalty-service.negotiation-type=plaintext

grpc.client.asset-service.address=static://asset-service:9094
grpc.client.asset-service.negotiation-type=plaintext

grpc.client.notification-service.address=static://notification-service:9095
grpc.client.notification-service.negotiation-type=plaintext

# Keycloak
keycloak.url=${KEYCLOAK_URL:http://localhost:8180}
keycloak.realm=master

# Service
service.name=identity-service
service.role=main
