input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  # Log từ Kong gateway
  if [service] {
    mutate {
      add_field => { "source" => "kong" }
      add_field => { "service_name" => "%{[service][name]}" }
    }
  }

  # Log từ microservices (qua logback)
  if [app_name] {
    mutate {
      add_field => { "source" => "microservice" }
      add_field => { "service_name" => "%{app_name}" }
    }
  }

  # Parse timestamp
  date {
    match => ["started_at", "UNIX_MS", "UNIX", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[source]:logs}-%{+YYYY.MM.dd}"
  }
}
