# gRPC Client - gọi tới các supporting services
grpc.client.loyalty-service.address=static://loyalty-service:9093
grpc.client.loyalty-service.negotiation-type=plaintext

grpc.client.asset-service.address=static://asset-service:9094
grpc.client.asset-service.negotiation-type=plaintext

grpc.client.notification-service.address=static://notification-service:9095
grpc.client.notification-service.negotiation-type=plaintext

# Service
service.name=voucher-service
service.role=main
